### ISSUE TITLE
Solve this Error !

### ISSUE THREAD

**Issue by sayandedotcom** [wpcodevo/nextauth-nextjs13-prisma#2]
![image](https://github.com/wpcodevo/nextauth-nextjs13-prisma/assets/107565578/e57568e2-2cba-4cbf-813e-9f21b09a21a5)

**Comment by wpcodevo** [comment]
> ![image](https://user-images.githubusercontent.com/107565578/254386543-e57568e2-2cba-4cbf-813e-9f21b09a21a5.png)

You're getting the Prisma Client Error because you haven't applied the necessary migrations to your database. To resolve this error, make sure to run the command `yarn prisma migrate dev` before starting Prisma Studio. This command will apply the pending migrations to synchronize your database schema.
